#server.port=80
#server.port.a=true
#server.port.b=true

# 自定义的配置参数
myUploadPath: d:/c76_blog/

server:
   port: 80

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/C76-S3-Ply-blog
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
  # 静态资源映射
  resources:
     staticLocations: 
        - classpath:/resources/
        - classpath:/static/
        - file:${myUploadPath}
  # 文件上传配置
  servlet:
     multipart:
        maxFileSize: 1000000000

  mail:
     # 邮箱服务器地址
     host: smtp.qq.com
     # 用户名
     username: 306529917@qq.com
     # 密码 
     password: sgbfaqcdhxdwbhda
     # 字符集编码
     default-encoding: UTF-8

# 以谁来发送邮件 自定义的参数
mail:
   fromMail:
      addr: 306529917@qq.com
      
mybatis:
  #实体类的路径
  type-aliases-package: com.yc.blog.bean
  configuration:
     map-underscore-to-camel-case: true
  
# 日志配置
logging:
  level:
    com:
      yc:
        blog:
          dao: debug
          web: warn
  
      
